### PR TITLE
Project#6: Request to merge "branch: feature" to Master

### PR DESCRIPTION
**Pull request by RailonA**
A Responsive Mobile, iPad, and Web page clone of The Next Web (https://thenextweb.com/). We used css grid and css flex to position all of the elements in this project.

### CODE REVIEW

**Review by layzrd — CHANGES_REQUESTED** [review]
### Status: Require changes 🌳 ♲
Hi @kimothokamau and @railonA, I am [Abdulaziz Redi Ali](https://azizali.ml/), your TSE for this PR.  👏👏  I appreciate your hard work in replicating thenextweb.com. Most requirements have been done 👌,  kindly fix the following issues.

[REQUIRED]

- [x] The search icon should be on the rightmost side of the sub-navigation row.

- [x] On medium screens, the TWN logo should appear at the leftmost part of the page.

- [x] On large screens, the TWN logo should appear on the leftmost part of the top news section.

- [x] In the "Latest News" section, "Latest Deals" section, and the "Latest Funding" section, articles should be aligned 4, 3, or 1 per row respectively on large, medium, and small screens.

- [x] In the Categories (Apps, Gear, Tech) section, articles should be aligned 3, 2, or 1 per row respectively on large, medium, and small screens.

- [x] Fix the latest deals section to make it the same as the original
latest deals original
latest deals section


- [x] The footer background color and styles should be similar to the original website.
footer replica

original footer

Once you fix the issues, kindly submit another code review. ♲

Happy coding 👨‍💻
[Abdulaziz Redi Ali](https://azizali.ml/) | [Contact me on Slack](https://microverse-students.slack.com/team/U011SD6JUH2)

**Comment by kimothokamau** [comment]
Thanks for the review and feedback, we have fixed the required changes and we request  another review

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

### Hi @RailonA and @kimothokamau 

Good job implementing the change as requested by the previous TSE :+1: 
However, there are still some changes that need to be made.

## [REQUIRED]
**Large Screen**
- [ ] Within the first 3 articles section, the first one to the left should have the TNW logo inside it.
- [ ] The font sizes you used in that aforementioned section is also smaller compared to the original
- [ ] Your page also has a scroll-bar at the bottom of the page which shouldn't be. Please, work on the width of the page.
- [ ] Add margin-left to your page (index) where necessary.

**Medium Screen**
- [ ] After the TNW logo at the top-left corner of the page, please, remove the empty space there.
- [ ] Add margin-left to your page (index) where necessary.

**Small Screen**
- [ ] The search bar and hamburger menu should be on a row and the navbar should be sticky

### Work on the required changes and request a new code review.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

### Hi @RailonA and @kimothokamau 

Good job implementing the change as requested by the previous TSE :+1: 
However, there are still some changes that need to be made.

## [REQUIRED]
**Large Screen**
- [x] The first 3 articles section should look exactly the same as it is on the original page.
- [x] Your page also has a scroll-bar at the bottom of the page which shouldn't be. Please, work on the width of the page.
- [x] Your page isn't uniformly aligned. `Latest News` and `latest funding rounds` section are not well aligned.
- [x] Your footer doesn't look like it is on the original page.

**Medium Screen**
- [x] The TNW logo inside the first image at the top shouldn't be there.
- [x] Work on the width. The scroll bar at the bottom of the page shouldn't be visible
- [x] The first three articles section has different height and width compared to the original.

**Small Screen**
- [x] The TNW logo inside the first image at the top shouldn't be there.
- [x] The navbar should be sticky

### Work on the required changes and request a new code review.

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by kimothokamau** [comment]
We have fixed the following required changes from the previous code review:  
**Large Screen**
- [x] The first 3 articles section should look exactly the same as it is on the original page.
- [x]  Your page also has a scroll-bar at the bottom of the page which shouldn't be. Please, work on the width of the page.
- [x]  Your page isn't uniformly aligned. Latest News and latest funding rounds section are not well aligned.
- [x]  Your footer doesn't look like it is on the original page.

**Medium Screen**
- [x] The TNW logo inside the first image at the top shouldn't be there.
- [x]  Work on the width. The scroll bar at the bottom of the page shouldn't be visible
- [x]  The first three articles section has different height and width compared to the original.


**Small Screen**
- [x] The TNW logo inside the first image at the top shouldn't be there.
- [x] The navbar should be sticky

Kindly review our code again

**Comment by mimipeshy** [comment]
## STATUS: CHANGES REQUIRED :recycle: 

Hey, team @RailonA and @kamaukk you guys have done amazingly well in implementing all changes as posted by TSE's :clap:  :clap: I really wanted to approve your project but you have to fix one more issue

- [ ] Fix stylelint errors

- [ ] Categories (Apps, Gear, Tech, etc) section
##### Medium version changes
 It aligns 2 category boxes per row ([link to page](https://thenextweb.com/))
 Check out screenshot below :arrow_down: 
Original
or

Clone
clone

That's all :relieved:  , kindly submit another review when done.

Regards
Peris Ndanu
Feel free to slack me anytime if you have any questions(perisndanu)

**Comment by kimothokamau** [comment]
Hello, we have fixed the medium screen to have 2 columns instead of 3 asper the last feedback. 
Please review our code again

**Comment by mimipeshy** [comment]
### STATUS :APPROVED :champagne:  :partying_face: 
Hey team @kimothokamau  and @RailonA  congratulations on completing this milestone! All checks have passed, go ahead and merge. All the best in future challenges !!!

Happy Coding :technologist: 
Regards
Peris Ndanu

**Pull request merged**
